builds:
  -
    main: '{{ if index .Env "MAIN_FILE" }}{{ .Env.MAIN_FILE }}{{ else }}cmd/main.go{{ end }}'
    goos:
      - $TARGET_OS
    goarch:
      - 'amd64'
      - 'arm64'
    goarm:
      - '8'
    env:
      - CC_linux_arm64=aarch64-linux-gnu-gcc
      - CC_linux_amd64=gcc
      - CC_darwin_arm64=gcc
      - CC_darwin_amd64=gcc
      - 'CC={{ index .Env (print "CC_" .Os "_" .Arch) }}'

release:
  name_template: "Release v{{.Version}}"
  mode: keep-existing
  replace_existing_draft: false
  draft: true
  disable: '{{ if index .Env "DISABLE_RELEASE" }}{{ .Env.DISABLE_RELEASE }}{{ else }}false{{ end }}'

archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ title .Os }}_{{ replace .Arch "amd64" "x86_64"  }}{{ if .Arm }}v{{ .Arm }}{{ end }}'

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ title .Env.TARGET_OS }}_checksums.txt"

snapshot:
  name_template: "{{ incminor .Version }}-next"
